apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7xwm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-efsx-tenant/rhtap-demo-app/hacbs-test-project-7xwm@sha256:13ea8ac937a5df6f004d0ae9d0e07dfe7c46f59d5f65c7c80b373d699f31f531
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
