apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7xwm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-efsx-tenant/rhtap-demo-app/hacbs-test-project-7xwm@sha256:002a8aeaf6532eef68b2d3d8b48d6f8814e31469a7183297d0faec508e4497a3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
